### ISSUE TITLE
attach comments to the source code instead of posting to the issue

### ISSUE THREAD

**Issue by yegor256** [savinmikhail/test_risk_zone_highlighter_action#2]
Currently, as I understand, comments are being posted as elements of a pull request discussion zone. It's not really convenient. Would be better to attach them right to the code, in the pull request.

**Comment by savinmikhail** [comment]
> Currently, as I understand, comments are being posted as elements of a pull request discussion zone. It's not really convenient. Would be better to attach them right to the code, in the pull request.

Thanks for submitting the issue. I take it into work for the next week.

**Comment by savinmikhail** [comment]
@yegor256, the v1.1.0 release is now posting comments directly to the changed lines. You can see it in the pending PR.
Any feedback to  the new functionality is welcome
